using System.Collections.Generic;
using GameRuntime.Room;

namespace GameRuntime
{
    public static class Config
    {
        public static RoomConfig startCfg = new RoomConfig()
            .Type(RoomType.Normal)
            .L("000000000D000000000")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("D      @          D")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("000000000D000000000");


        public static List<RoomConfig> normalCfg = new List<RoomConfig>()
        {
            new RoomConfig()
                .Type(RoomType.Battle)
                .L("000000000D000000000")
                .L("0                 0")
                .L("0  #           #  0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0        ###      0")
                .L("0       #000#     0")
                .L("D       #000#     D")
                .L("0       #000#     0")
                .L("0        ###      0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0  #           #  0")
                .L("0                 0")
                .L("000000000D000000000"),
            new RoomConfig()
                .Type(RoomType.Battle)
                .L("000000000D000000000")
                .L("0                 0")
                .L("0  #           #  0")
                .L("0  00         00  0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0     0  #  0     0")
                .L("D     0 #0# 0     D")
                .L("0     0  #  0     0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0  00         00  0")
                .L("0  #           #  0")
                .L("0                 0")
                .L("000000000D000000000"),
            new RoomConfig()
                .Type(RoomType.Battle)
                .L("000000000D000000000")
                .L("0                 0")
                .L("0  #           #  0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0   0    #  0   # 0")
                .L("0   0    #  0   # 0")
                .L("D   0    #  0   # D")
                .L("0   0    #  0   # 0")
                .L("0   0    #  0   # 0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0                 0")
                .L("0  #           #  0")
                .L("0                 0")
                .L("000000000D000000000"),
        };

        public static RoomConfig chestCfg = new RoomConfig()
            .Type(RoomType.Chest)
            .L("000000000D000000000")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("D        C        D")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("000000000D000000000");
        public static RoomConfig finishCfg = new RoomConfig()
            .Type(RoomType.Finish)
            .L("000000000D000000000")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("D     F           D")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("0                 0")
            .L("000000000D000000000");


    }
}